Repository kakao-tech-campus-2nd-step3/Team23_Android, pull requests merged in 2024-11, with the labels that each got.

#78 Test: 테스트 코드 작성
  app/src/main/java/com/kappzzang/jeongsan/di/DispatcherModule.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/addexpense/src/test/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModelTest.kt
  ui/creategroup/src/test/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModelTest.kt
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/sendmessage/SendMessageViewModelTest.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
  ui/main/src/test/java/com/kappzzang/jeongsan/main/MainPageViewModelTest.kt
Labels: ✅ Test

#87 Feat: Ocr, User 모듈 API 통합
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RoomModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  data/build.gradle.kts
  data/ocr/src/main/java/com/kappzzang/jeongsan/api/OcrRetrofitService.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/datasource/ReceiptCaptureRemoteDatasource.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/entity/OcrResultDetailItem.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/entity/ReceiptAnalyzeResponse.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/entity/ReceiptImage.kt
  data/user/src/main/java/com/kappzzang/jeongsan/api/ServiceAuthRetrofitService.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/AuthRemoteDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/AuthResponse.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/LoginRequest.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/RefreshResponse.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/RefreshTokenData.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/RefreshTokenRequest.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/RegisterRequest.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/TokenData.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseUseCaseModule.kt
Labels: ✨ Feature

#82 Test: Test코드 작성
  common/dispatcher/.gitignore
  common/dispatcher/build.gradle.kts
  common/dispatcher/proguard-rules.pro
  common/dispatcher/src/main/AndroidManifest.xml
  common/dispatcher/src/main/java/com/kappzzang/jeongsan/dispatcher/DispatcherModule.kt
  settings.gradle.kts
  ui/addexpense/build.gradle.kts
  ui/expensedetail/build.gradle.kts
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModel.kt
  ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModelTest.kt
  ui/expenselist/build.gradle.kts
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModel.kt
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModelTest.kt
  ui/login/build.gradle.kts
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/login/src/test/java/com/kappzzang/jeongsan/login/LoginViewModelTest.kt
  ui/main/build.gradle.kts
Labels: 🔨 Refactor, ✅ Test

#89 Refactor: Navigator 아키텍처 개선
  app/build.gradle.kts
  app/src/main/java/com/kappzzang/jeongsan/StartActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/di/NavigatorModule.kt
  app/src/main/java/com/kappzzang/jeongsan/navigation/NavigatorImpl.kt
  common/navigation/build.gradle.kts
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/AddExpenseNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/AppNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/CameraNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/CreateGroupNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/ExpenseDetailNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/ExpenseListNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/LoginNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/MainPageNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/SendMessageNavigator.kt
  settings.gradle.kts
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseActivity.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/di/NavigatorModule.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/navigation/AddExpenseNavigatorImpl.kt
  ui/camera/src/main/java/com/kappzzang/jeongsan/camera/ReceiptCameraActivity.kt
  ui/camera/src/main/java/com/kappzzang/jeongsan/camera/di/NavigatorModule.kt
  ui/camera/src/main/java/com/kappzzang/jeongsan/camera/navigation/CameraNavigatorImpl.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/di/NavigatorModule.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/navigation/CreateGroupNavigatorImpl.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/di/NavigatorModule.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/navigation/ExpenseDetailNavigatorImpl.kt
  ui/expenselist/src/main/AndroidManifest.xml
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/di/NavigatorModule.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/navigation/ExpenseListNavigatorImpl.kt
  ui/expenselist/src/main/res/values/strings.xml
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/di/NavigatorModule.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/navigation/LoginNavigatorImpl.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/di/NavigatorModule.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/navigation/MainPageNavigatorImpl.kt
  ui/sendmessage/.gitignore
  ui/sendmessage/build.gradle.kts
  ui/sendmessage/consumer-rules.pro
  ui/sendmessage/proguard-rules.pro
  ui/sendmessage/src/main/AndroidManifest.xml
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/MemberAdapter.kt
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/SendCompleteActivity.kt
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/SendMessageActivity.kt
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/SendMessageViewModel.kt
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/di/NavigatorModule.kt
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/navigation/SendMessageNavigatorImpl.kt
  ui/sendmessage/src/main/res/layout/activity_send_complete.xml
  ui/sendmessage/src/main/res/layout/activity_send_message.xml
  ui/sendmessage/src/main/res/layout/item_member_expense.xml
  ui/sendmessage/src/main/res/values/strings.xml
  ui/sendmessage/src/test/java/com/kappzzang/jeongsan/sendmessage/SendMessageViewModelTest.kt
Labels: 🔨 Refactor

#91 Feat: GroupModule API 통합
  data/group/src/main/java/com/kappzzang/jeongsan/api/GroupRetrofitService.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/group/GroupRemoteDataSource.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/CompleteGroupResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/CreateGroupResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GetGroupResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GetLinkResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GetMemberInfoResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GetMyExpenseResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GroupInfo.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/JoinGroupRequest.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/JoinGroupResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/MemberInfo.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/MemberPreview.kt
Labels: ✨ Feature

#88 Refactor: 리포지토리 구조 변경, Expense 모듈 내 Repository 구현
  data/expense/src/main/java/com/kappzzang/jeongsan/api/ReceiptRetrofitService.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseDetailRemoteDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseRepositoryModule.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/expensedetail/ExpenseDetailSelectionInfoEntity.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/expensedetail/UpdateExpenseDetailPayloadDTO.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/mapper/ExpenseEntityMapper.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseDetailFakeRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseDetailRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseFakeRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ReceiptRepositoryImpl.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseUseCaseModule.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/ExpenseDetailRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/ExpenseRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/ReceiptRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/EditExpenseDetailUseCase.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/GetExpenseDetailUseCase.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/GetExpenseListUseCase.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/GetExpenseUseCase.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/UploadExpenseUseCase.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseActivity.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/addexpense/src/test/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModelTest.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/intentcontract/AddExpenseContract.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/intentcontract/ExpenseDetailContract.kt
  ui/expensedetail/build.gradle.kts
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailActivity.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModel.kt
  ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModelTest.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListOnCalculationPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListPageViewModel.kt
Labels: ✨ Feature, 🔨 Refactor

#104 Feat: 로그인 우회 기능 구현
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
Labels: ⚙ Setting

#105 Fix: CreateGroupViewModel 테스트를 위한 IO Dispatcher 주입
  ui/camera/src/main/java/com/kappzzang/jeongsan/camera/ReceiptCameraViewModel.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/creategroup/src/test/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModelTest.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/CompleteExpenseListPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListOnCalculationPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/PendingExpenseListPageViewModel.kt
Labels: 🐞 Bug

#102 Feat: AddExpense내 카테고리 지정 다이얼로그 추가
  data/expense/src/main/java/com/kappzzang/jeongsan/api/ReceiptRetrofitService.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListFakeDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/CategoryEntity.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/GetCategoryListResponseDTO.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/mapper/ExpenseEntityMapper.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseFakeRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseCategory.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ReceiptItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/ExpenseRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/GetCategoryListUseCase.kt
  ui/addexpense/build.gradle.kts
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseActivity.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseBindingAdapter.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/colorpicker/CategoryListAdapter.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/colorpicker/ColorPickerDialog.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/colorpicker/ColorPickerViewModel.kt
  ui/addexpense/src/main/res/drawable/add_expense_color_dot.xml
  ui/addexpense/src/main/res/drawable/baseline_check_24.xml
  ui/addexpense/src/main/res/layout/activity_add_expense.xml
  ui/addexpense/src/main/res/layout/dialog_color_picker.xml
  ui/addexpense/src/main/res/layout/item_expense_category.xml
  ui/addexpense/src/main/res/values/strings.xml
  ui/addexpense/src/test/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModelTest.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseCategoryUIItem.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoDialogFragment.kt
Labels: ✨ Feature

#106 Feat: GroupModule이 RemoteDataSource를 사용하도록 구현
  data/group/build.gradle.kts
  data/group/src/main/java/com/kappzzang/jeongsan/api/GroupRetrofitService.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/remote/GroupRemoteDataSource.kt
  data/group/src/main/java/com/kappzzang/jeongsan/di/GroupRetrofitModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GetTargetGroupResponse.kt
  data/group/src/main/java/com/kappzzang/jeongsan/mapper/GroupEntityMapper.kt
  data/group/src/main/java/com/kappzzang/jeongsan/mapper/MemberEntityMapper.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/InviteRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/MemberRepositoryImpl.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/model/GroupCreateItem.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/GroupInfoRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/InviteRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/MemberRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetCurrentGroupInfoUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetInviteInfoUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/SendInviteMessageUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/UploadGroupInfoUseCase.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/creategroup/src/main/res/values/strings.xml
  ui/creategroup/src/test/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModelTest.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoDialogFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModel.kt
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModelTest.kt
Labels: ✨ Feature

#107 Feat: Retrofit의 Interceptor를 통한 토큰 관리
  common/androidutil/src/main/java/com/kappzzang/jeongsan/util/AuthenticationRepository.kt
  common/retrofit/build.gradle.kts
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/AuthInterceptor.kt
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/HeaderInterceptor.kt
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/RetrofitModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/api/GroupRetrofitService.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/remote/GroupRemoteDataSource.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/MemberRepositoryImpl.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/api/OcrRetrofitService.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/datasource/ReceiptCaptureRemoteDatasource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/AuthLocalDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/ServerAuthRemoteDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/di/RetrofitModule.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/RegisterRequest.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/AuthenticationRepositoryImpl.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ServerAuthenticationRepositoryImpl.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/repository/ServerAuthenticationRepository.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/AuthenticateWithServerUseCase.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
Labels: ✨ Feature

#110 Refactor: ExpenseList DTO 수정
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/expenselist/ExpenseListResponseDTO.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/expenselist/ExpenseRemoteEntity.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
  domain/expense/src/test/java/com/kappzzang/jeongsan/SendTransferMessageUseCaseTest.kt
  ui/expenselist/src/main/res/layout/fragment_pending_expense_list.xml
Labels: 🔨 Refactor

#114 Refactor: EncryptedSharedPreferences를 통한 토큰 저장
  app/build.gradle.kts
  app/src/main/java/com/kappzzang/jeongsan/JeongsanApplication.kt
  app/src/main/java/com/kappzzang/jeongsan/di/DatastoreModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/EncryptedSharedPreferencesModule.kt
  common/androidutil/src/main/java/com/kappzzang/jeongsan/util/AuthenticationRepository.kt
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/AuthInterceptor.kt
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/HeaderInterceptor.kt
  data/user/build.gradle.kts
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/AuthLocalDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/AuthenticationRepositoryImpl.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/AuthenticateWithKakaoUseCase.kt
Labels: 🔨 Refactor

#123 Feat: Logging Interceptor 추가
  common/retrofit/build.gradle.kts
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/AuthInterceptor.kt
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/HeaderInterceptor.kt
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/RetrofitModule.kt
Labels: ⚙ Setting

#124 Feat: Base64 인코딩 전 압축 기능 추가
  common/androidutil/src/main/java/com/kappzzang/jeongsan/util/Base64BitmapEncoder.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
Labels: ✨ Feature

#117 Feat: 사용자의 Service ID 관리 기능 추가
  common/androidutil/src/main/java/com/kappzzang/jeongsan/util/AuthenticationRepository.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/InviteRepositoryImpl.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/AuthLocalDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/mapper/KakaoUserInfoMapper.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/AuthenticationRepositoryImpl.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/di/UserUseCaseModule.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/model/UserItem.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/AuthenticateWithServerUseCase.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/GetUserServiceIdUseCase.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/SendTransferMessageUseCase.kt
  domain/group/build.gradle.kts
  domain/group/src/main/java/com/kappzzang/jeongsan/di/GroupUseCaseModule.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/model/GroupCreateItem.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/UploadGroupInfoUseCase.kt
  ui/build.gradle.kts
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/MemberUIData.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/res/layout/activity_main.xml
Labels: ✨ Feature

#128 Hotfix: OCR API 수정
  common/retrofit/build.gradle.kts
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/ResponseData.kt
  common/util/src/main/java/com/kappzzang/jeongsan/util/DateConverter.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/api/ReceiptRetrofitService.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseDetailRemoteDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/ImageEntity.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/api/OcrRetrofitService.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/datasource/ReceiptCaptureRemoteDatasource.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/entity/ReceiptImage.kt
Labels: 🐞 Bug

#137 Fix: 지출 업로드 후 크래시 현상 해결
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/ResponseWithExpenseIdDTO.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/mapper/ExpenseEntityMapper.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseActivity.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/data/ExpenseUploadUIState.kt
Labels: 🐞 Bug, 🔨 Refactor

#138 Refactor: Uuid로 명시된 필드 ServiceId로 수정
  common/androidutil/src/main/java/com/kappzzang/jeongsan/util/AuthenticationRepository.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/expenselist/ExpenseRemoteEntity.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/mapper/ExpenseEntityMapper.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/remote/GroupRemoteDataSource.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GroupInfo.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/ServerAuthRemoteDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/RegisterRequest.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/AuthenticationRepositoryImpl.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ServerAuthenticationRepositoryImpl.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/di/UserUseCaseModule.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/repository/ServerAuthenticationRepository.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/AuthenticateWithServerUseCase.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseItemWithCategory.kt
  domain/expense/src/test/java/com/kappzzang/jeongsan/SendTransferMessageUseCaseTest.kt
Labels: 🔨 Refactor

#139 Feat: ExpenseList UI 요소 개선
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseDetailFakeRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseFakeRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/ExpenseRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/ForceFetchExpenseListUseCase.kt
  ui/build.gradle.kts
  ui/expenselist/build.gradle.kts
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/CompleteExpenseListFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/PendingExpenseListFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/CompleteExpenseListPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListOnCalculationPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/PendingExpenseListPageViewModel.kt
  ui/expenselist/src/main/res/drawable/expense_list_chip_color.xml
  ui/expenselist/src/main/res/layout/fragment_complete_expense_list.xml
  ui/expenselist/src/main/res/layout/fragment_expense_list.xml
  ui/expenselist/src/main/res/layout/fragment_pending_expense_list.xml
  ui/main/build.gradle.kts
Labels: 🐞 Bug, ✨ Feature

#140 Feat: 그룹 참여하기 구현
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/GroupRemoteDataSource.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/group/GroupContract.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/group/GroupDao.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/group/GroupDatabase.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/member/MemberContract.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/member/MemberDao.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/member/MemberDatabase.kt
  data/group/src/main/java/com/kappzzang/jeongsan/di/GroupRetrofitModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/di/GroupRoomModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GroupEntity.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/MemberEntity.kt
  data/group/src/main/java/com/kappzzang/jeongsan/mapper/GroupEntityMapper.kt
  data/group/src/main/java/com/kappzzang/jeongsan/mapper/MemberEntityMapper.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/MemberRepositoryImpl.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/GroupInfoRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/JoinGroupUseCase.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/JoinGroupUIState.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
  ui/main/src/main/res/values/strings.xml
Labels: ✨ Feature

#143 Hotfix: 서버에서 보내는 Id값에 대한 DTO의 형식을 Long으로 수정
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GroupInfo.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
Labels: 🐞 Bug

#145 Fix: 앱 실행 시 강제 리프레시 코드 제거
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
Labels: 🔨 Refactor

#146 Fix: 결제자일 때만 결제 확인 정보 페이지에 접근할 수 있게 수정
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailActivity.kt
Labels: ⚙ Setting

#144 Feat: 지출 생성 시 카카오로 메시지를 전송하는 기능 구현
  app/src/main/java/com/kappzzang/jeongsan/StartActivity.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/ExpenseListNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/LoginNavigator.kt
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/MainPageNavigator.kt
  data/group/src/main/java/com/kappzzang/jeongsan/di/GroupRepositoryModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseMessageRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  domain/group/build.gradle.kts
  domain/group/src/main/java/com/kappzzang/jeongsan/di/GroupUseCaseModule.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/ExpenseMessageRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/GroupInfoRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetGroupMemberServiceIdUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/SendNewExpenseMessageUseCase.kt
  ui/addexpense/build.gradle.kts
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseActivity.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/data/ExpenseUploadUIState.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/intentcontract/ExpenseListContract.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/intentcontract/StartContract.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoDialogFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/navigation/ExpenseListNavigatorImpl.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/navigation/LoginNavigatorImpl.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/navigation/MainPageNavigatorImpl.kt
Labels: ✨ Feature

#148 Fix: 토큰 리프레시 안되는 문제 해결
  data/user/src/main/java/com/kappzzang/jeongsan/api/ServerAuthRetrofitService.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/ServerAuthRemoteDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/RefreshTokenRequest.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/AuthenticationRepositoryImpl.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
Labels: 🐞 Bug

#151 Fix: 테스트 코드 수정
  common/util/src/main/java/com/kappzzang/jeongsan/util/ColorParser.kt
  data/expense/src/test/java/com/kappzzang/jeongsan/ExpenseListEntityMapperTest.kt
  data/expense/src/test/java/com/kappzzang/jeongsan/ExpenseRoomEntityMapperTest.kt
  data/ocr/src/test/java/com/kappzzang/jeongsan/ReceiptCaptureRepositoryTest.kt
  domain/common-user/src/test/java/com/kappzzang/jeongsan/AuthenticateWithKakaoUseCaseTest.kt
  ui/addexpense/src/test/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModelTest.kt
  ui/creategroup/src/test/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModelTest.kt
  ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModelTest.kt
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModelTest.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/login/src/test/java/com/kappzzang/jeongsan/login/LoginViewModelTest.kt
  ui/main/src/test/java/com/kappzzang/jeongsan/main/MainPageViewModelTest.kt
Labels: ✅ Test

#152 Design: 지출 목록 디자인 개선
  app/src/main/res/values/themes.xml
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseUiItem.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/util/ExpenseUiItemMapper.kt
  ui/expenselist/src/main/res/drawable/expense_list_color_dot.xml
  ui/expenselist/src/main/res/drawable/expense_list_round_border.xml
  ui/expenselist/src/main/res/layout/fragment_complete_expense_list.xml
  ui/expenselist/src/main/res/layout/fragment_expense_list.xml
  ui/expenselist/src/main/res/layout/fragment_pending_expense_list.xml
  ui/expenselist/src/main/res/layout/item_expense.xml
  ui/expenselist/src/main/res/values/styles.xml
Labels: 🎨 Design

#153 Refactor: 로그인 로직 수정
  domain/common-user/src/main/java/com/kappzzang/jeongsan/di/UserUseCaseModule.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/AuthenticateWithServerUseCase.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/LoginOrRegisterUseCase.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/AppLoginState.kt
  ui/login/build.gradle.kts
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/login/src/main/res/layout/activity_login.xml
Labels: 🔨 Refactor

#154 Feat: 지출목록, 지출 상세 내역 UI 조정
  common/navigation/build.gradle.kts
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/ExpenseDetailNavigator.kt
  common/resource/src/main/res/values/dimen.xml
  data/expense/src/main/java/com/kappzzang/jeongsan/mapper/ExpenseListEntityMapper.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseItemWithCategory.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseActivity.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseUiItem.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/intentcontract/ExpenseDetailContract.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ButtonTextConverter.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailActivity.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModel.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/expensedetailpage/ExpenseDetailFragment.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/navigation/ExpenseDetailNavigatorImpl.kt
  ui/expensedetail/src/main/res/layout/activity_expense_detail.xml
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListBindingAdapter.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/util/ExpenseUiItemMapper.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListOnCalculationPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListViewModel.kt
  ui/expenselist/src/main/res/layout/item_expense.xml
Labels: 🎨 Design

#157 Feat: 테스트 계정으로 로그인 우회하는 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_icon-playstore.png
  app/src/main/res/drawable/ic_app_icon_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_icon_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_icon.webp
  app/src/main/res/mipmap-hdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon_round.webp
  build-config/build.gradle.kts
  common/resource/src/main/res/drawable/jeongsan_login_icon.png
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/LoginWithTestAccountUseCase.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseActivity.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/data/ExpenseUploadUIState.kt
  ui/addexpense/src/main/res/values/strings.xml
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/creategroup/src/main/res/values/strings.xml
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/login/src/main/res/layout/activity_login.xml
Labels: ✨ Feature

#158 Fix: 현재까지 발견된 문제점 수정
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/TransferItemEntity.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/expenselist/ExpenseRemoteEntity.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/api/GroupRetrofitService.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/GroupRemoteDataSource.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/CreateGroupRequestDTO.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/ConvertServiceIdToUuidUseCase.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/expensedetailpage/ExpenseDetailFragmentViewModel.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/expensedetailpage/ExpenseDetailItemListAdapter.kt
Labels: 🐞 Bug

#161 Test: 로그인 ViewModel 테스트 수정
  data/expense/src/test/java/com/kappzzang/jeongsan/ExpenseListEntityMapperTest.kt
  ui/login/src/test/java/com/kappzzang/jeongsan/login/LoginViewModelTest.kt
Labels: ✅ Test

#164 Design: 지출 목록 / 지출 상세 내역 디자인 수정
  app/src/main/java/com/kappzzang/jeongsan/JeongsanApplication.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseSelectionInfoUIData.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/selectionstatus/SelectionStatusViewModel.kt
  ui/expensedetail/src/main/res/layout/fragment_expense_detail.xml
  ui/expensedetail/src/main/res/layout/item_selection_item_header.xml
  ui/expenselist/src/main/res/layout/item_expense.xml
Labels: 🎨 Design

#165 Fix: 검증 중 발생한 문제 해결
  app/build.gradle.kts
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/error/JeongsanError.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/GroupRemoteDataSource.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/res/menu/menu_group_setting.xml
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
Labels: 🐞 Bug

#167 Fix: 지출 상세내역 롤백
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/expensedetailpage/ExpenseDetailFragmentViewModel.kt
Labels: 🐞 Bug

#166 Feat: 완료된 그룹을 숨기는 기능 구현
  common/resource/src/main/res/drawable/baseline_keyboard_arrow_up_24.xml
  ui/data/src/main/java/com/kappzzang/jeongsan/data/GroupViewItem.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/GroupListAdapter.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageBindingAdapter.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/animator/NoAnimationInGroupTitleAnimator.kt
  ui/main/src/main/res/layout/item_main_done_title.xml
  ui/main/src/main/res/layout/item_main_progress_title.xml
  ui/main/src/test/java/com/kappzzang/jeongsan/main/MainPageViewModelTest.kt
Labels: ✨ Feature

#169 Refactor: ExpenseList 리팩토링
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseDetailItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseDetailModel.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseListModel.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseListResponse.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseSelectionStatus.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseSelectionStatusItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseSelectorInfo.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ReceiptDetailItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ReceiptItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/Transfer.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/TransferMessage.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseListUIState.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/CompleteExpenseListFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/PendingExpenseListFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoDialogFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/util/CameraPermissionHelper.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/util/ExpenseStateConverter.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListPageViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListViewModel.kt
  ui/expenselist/src/main/res/layout/activity_expense_list.xml
Labels: 🔨 Refactor

#170 Test: 테스트 케이스 추가
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/expense/ExpenseContract.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/expense/ExpenseDao.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/expense/ExpenseDatabase.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseRoomModule.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/entity/expenselist/ExpenseRoomEntity.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/mapper/ExpenseListEntityMapper.kt
  data/expense/src/test/java/com/kappzzang/jeongsan/ExpenseDetailEntityMapperTest.kt
  domain/expense/src/test/java/com/kappzzang/jeongsan/ExpenseSelectionStatusTest.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/expensedetailpage/ExpenseDetailFragmentViewModel.kt
  ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModelTest.kt
  ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/SelectionStatusViewModelTest.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/AbstractExpenseListViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListViewModel.kt
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/ExpenseListFragmentViewModelTest.kt
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/ExpenseListViewModelTest.kt
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModelTest.kt
Labels: ✅ Test

#173 Design: 디자인 개선
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/activity_transfer_link_launch.xml
  app/src/main/res/values/themes.xml
  common/resource/src/main/res/drawable/main_group_item.xml
  ui/camera/src/main/res/layout/activity_receipt_camera.xml
  ui/creategroup/src/main/res/layout/activity_create_group.xml
Labels: 🎨 Design

#171 Test: 테스트 코드 추가 및 수정
  data/group/src/test/java/com/kappzzang/jeongsan/GroupEntityMapperTest.kt
  data/group/src/test/java/com/kappzzang/jeongsan/MemberEntityMapperTest.kt
  data/user/src/test/java/com/kappzzang/jeongsan/KakaoUserInfoMapperTest.kt
  data/user/src/test/java/com/kappzzang/jeongsan/TokenDataToServerAuthDataMapperTest.kt
  ui/camera/build.gradle.kts
  ui/camera/src/main/java/com/kappzzang/jeongsan/camera/ReceiptCameraViewModel.kt
  ui/camera/src/test/java/com/kappzzang/jeongsan/camera/ReceiptCameraViewModelTest.kt
  ui/creategroup/src/test/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModelTest.kt
  ui/main/src/test/java/com/kappzzang/jeongsan/main/MainPageViewModelTest.kt
  ui/sendmessage/src/test/java/com/kappzzang/jeongsan/sendmessage/SendMessageViewModelTest.kt
Labels: ✅ Test

#175 Feat: 에러 핸들링 개선
  ui/camera/src/test/java/com/kappzzang/jeongsan/camera/ReceiptCameraViewModelTest.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseDetailState.kt
  ui/expensedetail/build.gradle.kts
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ButtonTextConverter.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailActivity.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModel.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/expensedetailpage/ExpenseDetailFragment.kt
  ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/expensedetailpage/ExpenseDetailFragmentViewModel.kt
  ui/expensedetail/src/main/res/layout/activity_expense_detail.xml
  ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModelTest.kt
  ui/sendmessage/build.gradle.kts
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/SendMessageActivity.kt
  ui/sendmessage/src/main/java/com/kappzzang/jeongsan/sendmessage/SendMessageViewModel.kt
Labels: ✨ Feature

#176 Fix: OCR 이용 중 크래쉬 현상 해결
  data/ocr/src/main/java/com/kappzzang/jeongsan/entity/ReceiptAnalyzeResponse.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/mapper/OcrResultEntityMapper.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ReceiptCaptureRepositoryImpl.kt
Labels: 🐞 Bug

#177 Fix: 모임 종료 기능 롤백
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseListUIState.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/viewmodel/ExpenseListViewModel.kt
  ui/expenselist/src/main/res/menu/menu_group_setting.xml
  ui/expenselist/src/test/java/com/kappzzang/jeongsan/expenselist/ExpenseListViewModelTest.kt
Labels: 🐞 Bug

#178 Feat: 테스트 계정으로 로그인하는 기능 삭제
  app/build.gradle.kts
  build-config/build.gradle.kts
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/LoginWithTestAccountUseCase.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/login/src/test/java/com/kappzzang/jeongsan/login/LoginViewModelTest.kt
Labels: 🔨 Refactor

#180 Chore: Lint 수행
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
Labels: 🐞 Bug

#182 Fix: 서버 Url 변경에 따른 버전 업그레이드
  app/build.gradle.kts
Labels: 🐞 Bug
