Repository kakao-tech-campus-2nd-step3/Team23_Android, pull requests merged in 2024-09, with the labels that each got.

#5 Chore: 안드로이드 CI 스크립트 작성
  .editorconfig
  .github/workflows/dev.yml
  .github/workflows/post_merge_caching.yml
  .github/workflows/weekly_dev.yml
  app/build.gradle.kts
  app/src/main/java/com/kappzzang/jeongsan/ui/main/MainActivity.kt
Labels: 🌏 Deploy, ⚙ Setting

#7 Hotfix: Caching After Merge 워크플로 내 문법 오류 수정
  .github/workflows/post_merge_caching.yml
Labels: 🐞 Bug

#4 Feat: 메인 페이지 & 지출 내역 페이지 레이아웃 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/domain/model/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/domain/model/GroupItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/GroupViewType.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/MainActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/util/.gitkeep
  app/src/main/res/drawable/baseline_cached_24.xml
  app/src/main/res/drawable/baseline_check_24.xml
  app/src/main/res/drawable/baseline_keyboard_arrow_down_24.xml
  app/src/main/res/drawable/baseline_more_horiz_24.xml
  app/src/main/res/drawable/expense_list_bottom_nav.xml
  app/src/main/res/drawable/expense_list_bottom_nav_color.xml
  app/src/main/res/drawable/expense_list_chip_color.xml
  app/src/main/res/drawable/expense_list_item_background.xml
  app/src/main/res/drawable/icon_won_512.png
  app/src/main/res/drawable/main_create_group_button.xml
  app/src/main/res/drawable/main_group_item.xml
  app/src/main/res/layout/activity_add_expense.xml
  app/src/main/res/layout/activity_expense_detail.xml
  app/src/main/res/layout/activity_expense_list.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_expense_complete_list.xml
  app/src/main/res/layout/fragment_expense_list.xml
  app/src/main/res/layout/fragment_expense_pending_list.xml
  app/src/main/res/layout/item_expense.xml
  app/src/main/res/layout/item_main_done_title.xml
  app/src/main/res/layout/item_main_group.xml
  app/src/main/res/layout/item_main_progress_title.xml
  app/src/main/res/menu/menu_bottom_navigation.xml
  app/src/main/res/menu/menu_group_setting.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ Feature

#8 Chore: Gradle Dependency 수정
  .github/workflows/dev.yml
  .github/workflows/weekly_dev.yml
  app/build.gradle.kts
Labels: 🌏 Deploy, ⚙ Setting

#9 Feat: 로그인, 그룹 생성, 초대 현황, 정산 요청, 정산 완료 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/ui/HistoryActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/Member.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/MemberAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/creategroup/CreateGroupActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/inviteinfo/InviteInfoActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/login/LoginActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/sendcomplete/SendCompleteActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/sendmessage/SendMessageActivity.kt
  app/src/main/res/drawable/all_add.xml
  app/src/main/res/drawable/all_background_add_button.xml
  app/src/main/res/drawable/all_background_button.xml
  app/src/main/res/drawable/all_background_delete_button.xml
  app/src/main/res/drawable/all_background_frame.xml
  app/src/main/res/drawable/all_close.xml
  app/src/main/res/drawable/all_delete.xml
  app/src/main/res/drawable/kakao_login_large_narrow.png
  app/src/main/res/drawable/kakao_login_large_wide.png
  app/src/main/res/drawable/kakao_login_medium_narrow.png
  app/src/main/res/drawable/kakao_login_medium_wide.png
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/activity_invite_info.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_send_complete.xml
  app/src/main/res/layout/activity_send_message.xml
  app/src/main/res/layout/item_member.xml
  app/src/main/res/layout/item_member_expense.xml
  app/src/main/res/layout/item_member_info.xml
  app/src/main/res/layout/item_member_invite.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ Feature

#10 Feat: 프래그먼트 & 액티비티간 전환 설정
  app/build.gradle.kts
  app/src/main/java/com/kappzzang/jeongsan/domain/model/ExpenseItem.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/addexpense/AddExpenseActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/creategroup/CreateGroupActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expensedetail/ExpenseDetailActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/CompleteExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/PendingExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/MainActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/sendmessage/SendMessageActivity.kt
  app/src/main/res/layout/activity_expense_list.xml
  app/src/main/res/layout/fragment_complete_expense_list.xml
  app/src/main/res/layout/fragment_expense_complete_list.xml
  app/src/main/res/layout/fragment_expense_list.xml
  app/src/main/res/layout/fragment_expense_pending_list.xml
  app/src/main/res/layout/fragment_pending_expense_list.xml
  app/src/main/res/layout/item_expense.xml
  app/src/main/res/menu/menu_bottom_navigation.xml
  app/src/main/res/navigation/expense_list_nav_graph.xml
Labels: ✨ Feature

#11 Feat: 도메인 모델 생성
  app/src/main/java/com/kappzzang/jeongsan/domain/model/ExpenseItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/GroupItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/MemberItem.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/CompleteExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseViewItem.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/PendingExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupViewItem.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupViewType.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/MainActivity.kt
  app/src/main/res/layout/item_expense.xml
  app/src/main/res/layout/item_main_group.xml
Labels: ✨ Feature

#18 Feat: 메인 페이지 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/JeongsanApplication.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/group/GroupContract.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/group/GroupDao.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/group/GroupDatabase.kt
  app/src/main/java/com/kappzzang/jeongsan/data/entity/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/data/entity/GroupEntity.kt
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/GroupInfoRepositoryImpl.kt
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/UserInfoRepositoryImpl.kt
  app/src/main/java/com/kappzzang/jeongsan/di/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RoomModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/GroupItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/UserItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/GroupInfoRepository.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/UserInfoRepository.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/.gitkeep
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/GetDoneGroupUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/GetProgressingGroupUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/GetUserInfoUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupViewItem.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/GroupViewType.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/MainActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/main/MainPageViewModel.kt
  app/src/main/res/drawable/main_circle_image_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_main_group.xml
  app/src/main/res/values/dimen.xml
Labels: ✨ Feature

#19 Feat: 초대현황 페이지 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/kappzzang/jeongsan/JeongSanApplication.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/MemberContract.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/MemberDatabase.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/dao/MemberDao.kt
  app/src/main/java/com/kappzzang/jeongsan/data/entity/MemberEntity.kt
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/MemberRepositoryImpl.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RoomModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/MemberRepository.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/GetInviteInfoUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/MemberAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/inviteinfo/InviteInfoActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/inviteinfo/InviteInfoViewModel.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/inviteinfo/MemberInfoAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/inviteinfo/MemberInfoDiffUtil.kt
  app/src/main/res/layout/item_member_info.xml
Labels: ✨ Feature

#20 Feat: 지출 목록 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/ExpenseListFakeDatasource.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/expense/ExpenseContract.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/expense/ExpenseDao.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/expense/ExpenseDatabase.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/group/GroupDao.kt
  app/src/main/java/com/kappzzang/jeongsan/data/entity/ExpenseEntity.kt
  app/src/main/java/com/kappzzang/jeongsan/data/mapper/ExpenseEntityMapper.kt
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/ExpenseListFakeRepositoryImpl.kt
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/GroupInfoRepositoryImpl.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RoomModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/ExpenseItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/ExpenseListResponse.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/ExpenseListRepository.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/GroupInfoRepository.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/GetCurrentGroupInfoUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/GetExpenseListUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/CompleteExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListViewModel.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListViewUIData.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseViewItem.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/PendingExpenseListFragment.kt
  app/src/main/java/com/kappzzang/jeongsan/util/BindingAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/util/IntegerFormatter.kt
  app/src/main/res/layout/activity_expense_list.xml
  app/src/main/res/layout/fragment_complete_expense_list.xml
  app/src/main/res/layout/fragment_expense_list.xml
  app/src/main/res/layout/fragment_pending_expense_list.xml
  app/src/main/res/layout/item_expense.xml
  app/src/main/res/layout/item_main_group.xml
Labels: ✨ Feature

#23 Feat: 영수증 수정 & 수기 입력 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/ExpenseListFakeDatasource.kt
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/ReceiptRepositoryImpl.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/ReceiptDetailItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/ReceiptItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/ReceiptRepository.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/UploadExpenseUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/addexpense/AddExpenseActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/addexpense/AddExpenseViewModel.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/addexpense/ExpenseItemListAdapter.kt
  app/src/main/res/layout/activity_add_expense.xml
Labels: ✨ Feature

#22 Feat: 카메라 촬영 & 분석 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/ExpenseListFakeDatasource.kt
  app/src/main/java/com/kappzzang/jeongsan/data/datasource/ReceiptCaptureFakeDatasource.kt
  app/src/main/java/com/kappzzang/jeongsan/data/entity/OcrResultEntity.kt
  app/src/main/java/com/kappzzang/jeongsan/data/mapper/OcrResultEntityMapper.kt
  app/src/main/java/com/kappzzang/jeongsan/data/repositoryimpl/ReceiptCaptureRepositoryImpl.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/ExpenseDetailItem.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/model/OcrResultResponse.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/repository/ReceiptCaptureRepository.kt
  app/src/main/java/com/kappzzang/jeongsan/domain/usecase/AnalyzeReceiptImageUseCase.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/addexpense/AddExpenseActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/addexpense/AddExpenseViewModel.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/camera/ReceiptCameraActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/camera/ReceiptCameraViewModel.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/expenselist/ExpenseListAdapter.kt
  app/src/main/java/com/kappzzang/jeongsan/util/Base64BitmapEncoder.kt
  app/src/main/java/com/kappzzang/jeongsan/util/IntentHelper.kt
  app/src/main/res/animator/dot_morph_first.xml
  app/src/main/res/animator/dot_morph_fourth.xml
  app/src/main/res/animator/dot_morph_second.xml
  app/src/main/res/animator/dot_morph_third.xml
  app/src/main/res/drawable/baseline_add_a_photo_24.xml
  app/src/main/res/drawable/baseline_edit_document_24.xml
  app/src/main/res/drawable/dot_animation.xml
  app/src/main/res/drawable/icon_won.xml
  app/src/main/res/drawable/receipt_camera_sending_picture.xml
  app/src/main/res/drawable/receipt_camera_shutter.xml
  app/src/main/res/drawable/receipt_camera_shutter_normal.xml
  app/src/main/res/drawable/receipt_camera_shutter_selected.xml
  app/src/main/res/layout/activity_add_expense.xml
  app/src/main/res/layout/activity_expense_list.xml
  app/src/main/res/layout/activity_receipt_camera.xml
  app/src/main/res/menu/menu_add_expense.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ Feature, 🎨 Design

#24 Hotfix: CI 캐싱 문제 해결
  .github/workflows/post_merge_caching.yml
Labels: 🐞 Bug, ⚙ Setting

#25 Docs: PR 템플릿 추가
  .github/pull_request_template.md
Labels: 📃 Docs

#28 Hotfix: Merge시 빌드 실패 오류 해결
  .github/workflows/post_merge_caching.yml
Labels: 🐞 Bug
