Repository kakao-tech-campus-2nd-step3/Team23_Android, pull requests merged in 2024-10, with the labels that each got.

#35 Hotfix: 모듈 이름 변경 & JVM Target 통일
  app/build.gradle.kts
  data/build.gradle.kts
  domain/build.gradle.kts
  settings.gradle.kts
  ui/build.gradle.kts
Labels: 🐞 Bug

#37 Refactor: GroupModule 의존성 적용 및 import 오류 해결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/ui/HistoryActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/ui/Member.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/group/build.gradle.kts
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/group/GroupDao.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/group/GroupDatabase.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/member/MemberDao.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/member/MemberDatabase.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/GroupEntity.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/MemberEntity.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/MemberRepositoryImpl.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/GroupInfoRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/MemberRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetCurrentGroupInfoUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetDoneGroupUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetInviteInfoUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetProgressingGroupUseCase.kt
  ui/build.gradle.kts
  ui/creategroup/build.gradle.kts
  ui/creategroup/src/main/AndroidManifest.xml
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/res/layout/activity_create_group.xml
  ui/creategroup/src/main/res/layout/item_member_invite.xml
  ui/creategroup/src/main/res/values-night/themes.xml
  ui/creategroup/src/main/res/values/array.xml
  ui/creategroup/src/main/res/values/strings.xml
  ui/creategroup/src/main/res/values/themes.xml
  ui/data/build.gradle.kts
  ui/data/src/main/java/com/kappzzang/jeongsan/data/GroupViewItem.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/data/Member.kt
  ui/expenselist/build.gradle.kts
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/MemberAdapter.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/sendmessage/SendMessageActivity.kt
  ui/expenselist/src/main/res/layout/activity_expense_list.xml
  ui/expenselist/src/main/res/layout/activity_send_message.xml
  ui/expenselist/src/main/res/layout/item_member_info.xml
  ui/expenselist/src/main/res/values/strings.xml
  ui/main/build.gradle.kts
  ui/main/src/main/AndroidManifest.xml
  ui/main/src/main/java/com/kappzzang/jeongsan/main/GroupListAdapter.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
  ui/main/src/main/res/layout/activity_main.xml
  ui/main/src/main/res/values/strings.xml
Labels: 🔨 Refactor

#42 Refactor: 모듈 간 DI 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/StartActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/di/NavigatorModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/ReceiptCaptureRepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RoomModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  app/src/main/java/com/kappzzang/jeongsan/navigation/NavigatorImpl.kt
  app/src/main/res/layout/activity_history.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/values/strings.xml
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/AppNavigator.kt
  ui/addexpense/src/main/AndroidManifest.xml
  ui/expensedetail/src/main/AndroidManifest.xml
  ui/expenselist/src/main/res/values/strings.xml
  ui/login/build.gradle.kts
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
Labels: 🔨 Refactor

#50 Feat: 로그인 기능 구현
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/JeongsanApplication.kt
  app/src/main/java/com/kappzzang/jeongsan/StartActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/di/DatastoreModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RetrofitModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  build.gradle.kts
  common/androidutil/src/main/java/com/kappzzang/jeongsan/data/AuthData.kt
  common/androidutil/src/main/java/com/kappzzang/jeongsan/util/AuthenticationRepository.kt
  common/datastore/.gitignore
  common/datastore/build.gradle.kts
  common/datastore/src/main/java/com/kappzzang/jeongsan/datastore/UserPreferencesModule.kt
  common/retrofit/.gitignore
  common/retrofit/build.gradle.kts
  common/retrofit/src/main/java/com/kappzzang/jeongsan/retrofit/RetrofitModule.kt
  data/build.gradle.kts
  data/user/build.gradle.kts
  data/user/src/main/java/com/kappzzang/jeongsan/api/KakaoAuthRetrofitService.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/AuthLocalDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/datasource/KakaoAuthenticationDataSource.kt
  data/user/src/main/java/com/kappzzang/jeongsan/entity/KakaoRefreshTokenDTO.kt
  data/user/src/main/java/com/kappzzang/jeongsan/mapper/KakaoOAuthTokenAuthDataMapper.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/AuthenticationRepositoryImpl.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/KakaoAuthenticationRepositoryImpl.kt
  domain/user/build.gradle.kts
  domain/user/src/main/java/com/kappzzang/jeongsan/model/AppLoginStatus.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/model/AuthenticationResult.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/repository/KakaoAuthenticationRepository.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/repository/KakaoAuthorizationRepository.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/repository/ServerAuthenticationRepository.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/usecase/AuthenticateWithKakaoUseCase.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/usecase/AuthorizeWithKakaoUseCase.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/usecase/RegisterWithKakaoUseCase.kt
  settings.gradle.kts
  ui/build.gradle.kts
  ui/data/src/main/java/com/kappzzang/jeongsan/data/KakaoAuthorizeScope.kt
  ui/login/build.gradle.kts
  ui/login/proguard-rules.pro
  ui/login/src/main/AndroidManifest.xml
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/login/src/main/res/layout/activity_login.xml
  ui/login/src/main/res/values/strings.xml
Labels: ✨ Feature

#51 Feat: 송금 요청 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/TransferLinkLaunchActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  app/src/main/java/com/kappzzang/jeongsan/navigation/NavigatorImpl.kt
  app/src/main/res/layout/activity_transfer_link_launch.xml
  common/navigation/src/main/java/com/kappzzang/jeongsan/navigation/AppNavigator.kt
  data/expense/build.gradle.kts
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/TransferRepositoryImpl.kt
  data/user/src/main/java/com/kappzzang/jeongsan/mapper/KakaoUserInfoMapper.kt
  data/user/src/main/java/com/kappzzang/jeongsan/repositoryimpl/UserInfoRepositoryImpl.kt
  domain/expense/build.gradle.kts
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/TransferDetailItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/TransferRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/GetTransferInfoUseCase.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/SendTransferMessageUseCase.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/model/UserItem.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/repository/UserInfoRepository.kt
  domain/user/src/main/java/com/kappzzang/jeongsan/usecase/GetUserInfoUseCase.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/MemberAdapter.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/sendmessage/MemberAdapter.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/sendmessage/SendMessageActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/sendmessage/SendMessageViewModel.kt
  ui/expenselist/src/main/res/layout/item_member_expense.xml
  ui/expenselist/src/main/res/values/strings.xml
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
Labels: ✨ Feature

#52 Feat: 모임 생성 페이지 구현
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/datasource/group/GroupDatabase.kt
  data/group/src/main/java/com/kappzzang/jeongsan/mapper/GroupEntityMapper.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/GroupInfoRepositoryImpl.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/model/GroupCreateItem.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/GroupInfoRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/UploadGroupInfoUseCase.kt
  ui/creategroup/build.gradle.kts
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/MemberAdapter.kt
  ui/creategroup/src/main/res/layout/activity_create_group.xml
  ui/creategroup/src/main/res/layout/item_member_invite.xml
  ui/creategroup/src/main/res/values/strings.xml
  ui/data/src/main/java/com/kappzzang/jeongsan/data/MemberUIData.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
Labels: ✨ Feature

#54 Chore: Lint 수행
  common/datastore/src/main/java/com/kappzzang/jeongsan/datastore/UserPreferencesModule.kt
Labels: 🐞 Bug

#61 Refactor: 초대 현황 페이지를 Dialog로 수정
  common/resource/src/main/res/drawable/invite_info_dialog_background.xml
  common/resource/src/main/res/values/dimen.xml
  ui/expenselist/src/main/AndroidManifest.xml
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoActivity.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoDialogFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModel.kt
  ui/expenselist/src/main/res/layout/fragment_invite_info_dialog.xml
Labels: 🔨 Refactor

#63 Fix: 워크플로에서 Git Secrets 불러오는 스크립트 추가
  .github/workflows/dev.yml
  .github/workflows/post_merge_caching.yml
  .github/workflows/weekly_dev.yml
Labels: ⚙ Setting

#64 Refactor: 리뷰 요청사항 반영
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RoomModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseRepositoryModule.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseRoomModule.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseUseCaseModule.kt
  ui/camera/src/main/java/com/kappzzang/jeongsan/camera/ReceiptCameraActivity.kt
  ui/creategroup/proguard-rules.pro
Labels: 🔨 Refactor

#65 Refactor: 리뷰 요청사항 반영
  app/build.gradle.kts
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/di/OcrRepositoryModule.kt
  data/user/build.gradle.kts
  data/user/src/main/java/com/kappzzang/jeongsan/di/RetrofitModule.kt
  data/user/src/main/java/com/kappzzang/jeongsan/di/UserRepositoryModule.kt
  domain/common-user/.gitignore
  domain/common-user/build.gradle.kts
  domain/common-user/src/main/java/com/kappzzang/jeongsan/di/UserUseCaseModule.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/model/AppLoginStatus.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/model/AuthenticationResult.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/model/UserItem.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/repository/KakaoAuthenticationRepository.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/repository/KakaoAuthorizationRepository.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/repository/ServerAuthenticationRepository.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/repository/UserInfoRepository.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/AuthenticateWithKakaoUseCase.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/AuthorizeWithKakaoUseCase.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/GetUserInfoUseCase.kt
  domain/common-user/src/main/java/com/kappzzang/jeongsan/usecase/RegisterWithKakaoUseCase.kt
  domain/expense/build.gradle.kts
  domain/ocr/src/main/java/com/kappzzang/jeongsan/di/OcrUseCaseModule.kt
  settings.gradle.kts
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
  ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/ExpenseItemListAdapter.kt
  ui/addexpense/src/main/res/layout/item_expense_item.xml
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/creategroup/src/main/res/layout/activity_create_group.xml
  ui/data/src/main/java/com/kappzzang/jeongsan/data/ExpenseItemInput.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoDialogFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/sendmessage/SendMessageActivity.kt
  ui/login/build.gradle.kts
  ui/main/build.gradle.kts
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
Labels: 🔨 Refactor

#66 Feat: 초대 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kappzzang/jeongsan/StartActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  common/resource/src/main/res/color/selector_invite_button_color.xml
  common/resource/src/main/res/drawable/all_background_button.xml
  common/resource/src/main/res/values/colors.xml
  data/group/build.gradle.kts
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/InviteRepositoryImpl.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/repository/InviteRepository.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetInviteInfoUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/SendInviteMessageUseCase.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupActivity.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoDialogFragment.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/MemberInfoAdapter.kt
  ui/expenselist/src/main/res/layout/item_member_info.xml
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainActivity.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
  ui/main/src/main/res/values/strings.xml
Labels: ✨ Feature, 🔨 Refactor

#70 Refactor: 리뷰요청사항 반영
  app/src/main/java/com/kappzzang/jeongsan/StartActivity.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RepositoryModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/RoomModule.kt
  app/src/main/java/com/kappzzang/jeongsan/di/UseCaseModule.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/di/ExpenseRepositoryModule.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseFakeRepositoryImpl.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/di/GroupRepositoryModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/di/GroupRoomModule.kt
  data/group/src/main/java/com/kappzzang/jeongsan/entity/MemberEntity.kt
  data/group/src/main/java/com/kappzzang/jeongsan/mapper/MemberEntityMapper.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/InviteRepositoryImpl.kt
  data/group/src/main/java/com/kappzzang/jeongsan/repositoryimpl/MemberRepositoryImpl.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/ExpenseListRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/repository/ExpenseRepository.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/GetExpenseListUseCase.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/di/GroupUseCaseModule.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/model/MemberItem.kt
  domain/group/src/main/java/com/kappzzang/jeongsan/usecase/GetInviteInfoUseCase.kt
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/data/src/main/java/com/kappzzang/jeongsan/intentcontract/StartContract.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/InviteInfoViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/MemberInfoAdapter.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/inviteinfo/MemberInfoDiffUtil.kt
  ui/expenselist/src/main/res/layout/item_member_info.xml
  ui/expenselist/src/main/res/values/strings.xml
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginActivity.kt
  ui/login/src/main/java/com/kappzzang/jeongsan/login/LoginViewModel.kt
  ui/main/src/main/java/com/kappzzang/jeongsan/main/MainPageViewModel.kt
Labels: 🔨 Refactor

#69 Test: 테스트 코드 작성
  common/util/build.gradle.kts
  common/util/src/main/java/com/kappzzang/jeongsan/util/DateConverter.kt
  common/util/src/test/java/com/kappzzang/jeongsan/DateConverterTest.kt
  common/util/src/test/java/com/kappzzang/jeongsan/IntegerFormatterTest.kt
  data/build.gradle.kts
  data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListFakeDatasource.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/mapper/ExpenseEntityMapper.kt
  data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseFakeRepositoryImpl.kt
  data/expense/src/test/java/com/kappzzang/jeongsan/ExpenseEntityMapperTest.kt
  data/ocr/src/main/java/com/kappzzang/jeongsan/mapper/OcrResultEntityMapper.kt
  data/ocr/src/test/java/com/kappzzang/jeongsan/OcrResultEntityMapperTest.kt
  data/ocr/src/test/java/com/kappzzang/jeongsan/ReceiptCaptureRepositoryTest.kt
  data/user/src/test/java/com/kappzzang/jeongsan/KakaoOAuthTokenAuthDataMapperTest.kt
  domain/build.gradle.kts
  domain/common-user/src/test/java/com/kappzzang/jeongsan/AuthenticateWithKakaoUseCaseTest.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/model/ExpenseItem.kt
  domain/expense/src/main/java/com/kappzzang/jeongsan/usecase/SendTransferMessageUseCase.kt
  domain/expense/src/test/java/com/kappzzang/jeongsan/SendTransferMessageUseCaseTest.kt
  domain/ocr/src/main/java/com/kappzzang/jeongsan/model/OcrResultResponse.kt
  ui/build.gradle.kts
  ui/creategroup/src/main/java/com/kappzzang/jeongsan/creategroup/CreateGroupViewModel.kt
  ui/expenselist/src/main/java/com/kappzzang/jeongsan/expenselist/ExpenseListAdapter.kt
Labels: 🔨 Refactor, ✅ Test
